{"name": "Successful Login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up\n    at UIA2Proxy.command (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\jsonwp-proxy\\proxy.js:274:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at AndroidUiautomator2Driver.commands.pressKeyCode (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-driver\\lib\\commands\\actions.js:6:10)\n", "trace": "  File \"H:\\GitHub\\appium-python-automation\\appium-python-automation\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"H:\\GitHub\\appium-python-automation\\appium-python-automation\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_steps.py\", line 6, in open_login_page\n    context.app.launch_page.login_with_existing_account()\n  File \"H:\\GitHub\\appium-python-automation\\appium-python-automation\\features\\pages\\launch_page.py\", line 13, in login_with_existing_account\n    self.type_phone()\n  File \"H:\\GitHub\\appium-python-automation\\appium-python-automation\\features\\pages\\base_page.py\", line 45, in type_phone\n    element.press_keycode(0x0000000e)\n  File \"H:\\GitHub\\appium-python-automation\\appium-python-automation\\venv\\lib\\site-packages\\appium\\webdriver\\extensions\\keyboard.py\", line 102, in press_keycode\n    self.execute(Command.PRESS_KEYCODE, data)\n  File \"H:\\GitHub\\appium-python-automation\\appium-python-automation\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 444, in execute\n    self.error_handler.check_response(response)\n  File \"H:\\GitHub\\appium-python-automation\\appium-python-automation\\venv\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 30, in check_response\n    raise wde\n  File \"H:\\GitHub\\appium-python-automation\\appium-python-automation\\venv\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 26, in check_response\n    super().check_response(response)\n  File \"H:\\GitHub\\appium-python-automation\\appium-python-automation\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 249, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given I open login page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up\n    at UIA2Proxy.command (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\jsonwp-proxy\\proxy.js:274:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at AndroidUiautomator2Driver.commands.pressKeyCode (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-uiautomator2-driver\\lib\\commands\\actions.js:6:10)\n", "trace": "  File \"H:\\GitHub\\appium-python-automation\\appium-python-automation\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"H:\\GitHub\\appium-python-automation\\appium-python-automation\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_steps.py\", line 6, in open_login_page\n    context.app.launch_page.login_with_existing_account()\n  File \"H:\\GitHub\\appium-python-automation\\appium-python-automation\\features\\pages\\launch_page.py\", line 13, in login_with_existing_account\n    self.type_phone()\n  File \"H:\\GitHub\\appium-python-automation\\appium-python-automation\\features\\pages\\base_page.py\", line 45, in type_phone\n    element.press_keycode(0x0000000e)\n  File \"H:\\GitHub\\appium-python-automation\\appium-python-automation\\venv\\lib\\site-packages\\appium\\webdriver\\extensions\\keyboard.py\", line 102, in press_keycode\n    self.execute(Command.PRESS_KEYCODE, data)\n  File \"H:\\GitHub\\appium-python-automation\\appium-python-automation\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 444, in execute\n    self.error_handler.check_response(response)\n  File \"H:\\GitHub\\appium-python-automation\\appium-python-automation\\venv\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 30, in check_response\n    raise wde\n  File \"H:\\GitHub\\appium-python-automation\\appium-python-automation\\venv\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 26, in check_response\n    super().check_response(response)\n  File \"H:\\GitHub\\appium-python-automation\\appium-python-automation\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 249, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1670604928460, "stop": 1670604934027}, {"name": "When I login with email and password", "status": "skipped", "start": 1670604934178, "stop": 1670604934178}, {"name": "Then I am on main page", "status": "skipped", "start": 1670604934178, "stop": 1670604934178}], "start": 1670604921880, "stop": 1670604934178, "uuid": "d5f27752-e9dc-4e2c-ac3a-276a31f2df60", "historyId": "cff43881b2ec95557ed8ff74700e3a25", "fullName": "Tests for MyWorkDoc application: Successful Login", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Tests for MyWorkDoc application"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}